# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurants', '0005_job_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='myrestaurants')),
                ('order', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, default=0)),
                ('height', models.PositiveIntegerField(blank=True, default=0)),
                ('active', models.BooleanField(default=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myrestaurants.Job')),
            ],
        ),
    ]
