# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-26 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_management', '0005_auto_20180624_1318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
