# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-27 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_management', '0009_auto_20180627_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
    ]
