# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-27 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cost_management', '0011_auto_20180627_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense2',
            name='expense_ptr',
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense2',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense2',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expense2',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
