# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-27 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_management', '0012_auto_20180627_1230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense2',
        ),
    ]
